### PR TITLE
[feature2] This is second feature

### PR DESCRIPTION
**Pull request by yeno-bidu**
This is just a pseudo feature which does not constitute to anything, but helps us understand how pull requests works -
1. when a non-collaborator creates the pull request
2. when required number of collaborators reviews and rejects the pull request
3. when relevants changes are made/committed/pushed into the feature branch

### CODE REVIEW

**Review by yeno-bidu — COMMENTED** [review]
I as a non-collaborator feel the changes are good..

**Review by shashikiran-pallavi — CHANGES_REQUESTED** [review]
Alrighty alrighty then !!!

**Review by shashikiran-alloli — CHANGES_REQUESTED** [review]
I'm not sure about how it helps and what it does.. please add more description in your feature pull request

**Comment by yeno-bidu** [comment]
Have made revelevant changes, kindly approve!

**Review by hangonshashi — APPROVED** [review]
Alright, seems to be good be merged!

**Review by shashikiran-pallavi — APPROVED** [review]
Although it does not help in any way, it does not harm either to merge into the main branch.

**Review by shashikiran-alloli — APPROVED** [review]
Good the see the description added to the feature2.

**Pull request merged**
